IR.onPressEvent(RemoteButton.Up, function () {
    SuperBit.MotorRun(SuperBit.enMotors.M1, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, -255)
})
IR.onPressEvent(RemoteButton.Down, function () {
    SuperBit.MotorRun(SuperBit.enMotors.M1, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, -255)
})
IR.onPressEvent(RemoteButton.Minus, function () {
    SuperBit.MotorRun(SuperBit.enMotors.M1, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, 255)
})
IR.onPressEvent(RemoteButton.Right, function () {
    SuperBit.RGB_Program().showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(100)
    SuperBit.RGB_Program().showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(100)
    SuperBit.RGB_Program().showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(100)
    SuperBit.RGB_Program().showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(100)
    SuperBit.MotorRun(SuperBit.enMotors.M1, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, -255)
    basic.showIcon(IconNames.Heart)
    SuperBit.MotorRun(SuperBit.enMotors.M1, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, 255)
    basic.showIcon(IconNames.Heart)
    SuperBit.MotorRun(SuperBit.enMotors.M1, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, 255)
    basic.showIcon(IconNames.Heart)
    SuperBit.MotorRun(SuperBit.enMotors.M1, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, -255)
    basic.showIcon(IconNames.Heart)
    SuperBit.MotorRun(SuperBit.enMotors.M1, 0)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 0)
    SuperBit.MotorRun(SuperBit.enMotors.M3, 0)
    SuperBit.MotorRun(SuperBit.enMotors.M4, 0)
    basic.showIcon(IconNames.Happy)
    basic.pause(3000)
    basic.showIcon(IconNames.Heart)
    SuperBit.MotorRun(SuperBit.enMotors.M1, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, 255)
    basic.showIcon(IconNames.Heart)
    SuperBit.MotorRun(SuperBit.enMotors.M1, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, -255)
    basic.showIcon(IconNames.Heart)
    SuperBit.Music(SuperBit.enMusic.chase)
    basic.showIcon(IconNames.Heart)
    SuperBit.MotorRun(SuperBit.enMotors.M1, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, -255)
    basic.showIcon(IconNames.Happy)
    SuperBit.MotorRun(SuperBit.enMotors.M1, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, -255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, 255)
    SuperBit.Music(SuperBit.enMusic.nyan)
})
IR.onPressEvent(RemoteButton.OK, function () {
    SuperBit.MotorRun(SuperBit.enMotors.M1, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M2, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M3, 255)
    SuperBit.MotorRun(SuperBit.enMotors.M4, 255)
})
IR.onPressEvent(RemoteButton.Back, function () {
    SuperBit.Music(SuperBit.enMusic.nyan)
    SuperBit.Music(SuperBit.enMusic.entertainer)
    SuperBit.Music(SuperBit.enMusic.jump_up)
    SuperBit.Music(SuperBit.enMusic.birthday)
    for (let index = 0; index < 3; index++) {
        basic.showIcon(IconNames.Happy)
    }
    basic.showIcon(IconNames.Heart)
})
let strip = 0
IR.init(Pins.P3)
basic.forever(function () {
    strip = sonar.ping(
    DigitalPin.P1,
    DigitalPin.P2,
    PingUnit.Centimeters
    )
    if (strip < 5) {
        SuperBit.Music(SuperBit.enMusic.power_up)
    }
})
